intent_map={
    0:'activate_my_card',
    1:'age_limit',
    2:'apple_pay_or_google_pay',
    3:'atm_support',
    4:'automatic_top_up',
    5:'balance_not_updated_after_bank_transfer',
    6:'balance_not_updated_after_cheque_or_cash_deposit',
    7:'beneficiary_not_allowed',
    8:'cancel_transfer',
    9:'card_about_to_expire',
    10:'card_acceptance',
    11:'card_arrival',
    12:'card_delivery_estimate',
    13:'card_linking',
    14:'card_not_working',
    15:'card_payment_fee_charged',
    16:'card_payment_not_recognised',
    17:'card_payment_wrong_exchange_rate',
    18:'card_swallowed',
    19:'cash_withdrawal_charge',
    20:'cash_withdrawal_not_recognised',
    21:'change_pin',
    22:'compromised_card',
    23:'contactless_not_working',
    24:'country_support',
    25:'declined_card_payment',
    26:'declined_cash_withdrawal',
    27:'declined_transfer',
    28:'direct_debit_payment_not_recognised',
    29:'disposable_card_limits',
    30:'edit_personal_details',
    31:'exchange_charge',
    32:'exchange_rate',
    33:'exchange_via_app',
    34:'extra_charge_on_statement',
    35:'failed_transfer',
    36:'fiat_currency_support',
    37:'get_disposable_virtual_card',
    38:'get_physical_card',
    39:'getting_spare_card',
    40:'getting_virtual_card',
    41:'lost_or_stolen_card',
    42:'lost_or_stolen_phone',
    43:'order_physical_card',
    44:'passcode_forgotten',
    45:'pending_card_payment',
    46:'pending_cash_withdrawal',
    47:'pending_top_up',
    48:'pending_transfer',
    49:'pin_blocked',
    50:'receiving_money',
    51:'Refund_not_showing_up',
    52:'request_refund',
    53:'reverted_card_payment',
    54:'supported_cards_and_currencies',
    55:'terminate_account',
    56:'top_up_by_bank_transfer_charge',
    57:'top_up_by_card_charge',
    58:'top_up_by_cash_or_cheque',
    59:'top_up_failed',
    60:'top_up_limits',
    61:'top_up_reverted',
    62:'topping_up_by_card',
    63:'transaction_charged_twice',
    64:'transfer_fee_charged',
    65:'transfer_into_account',
    66:'transfer_not_received_by_recipient',
    67:'transfer_timing',
    68:'unable_to_verify_identity',
    69:'verify_my_identity',
    70:'verify_source_of_funds',
    71:'verify_top_up',
    72:'virtual_card_not_working',
    73:'visa_or_mastercard',
    74:'why_verify_identity',
    75:'wrong_amount_of_cash_received',
    76:'wrong_exchange_rate_for_cash_withdrawal',
    77:'greet',
    78:'goodbye',
    79:'authenticate',
    80:'balance_inquiry',
    81:'transfer',
    82:'log_out',
    83:'transaction',
    84:'loan_status',
    85:'status',
    86:'bank_add',
    87:'info',
    88:'loan_amt',
    89:'loan_doc'
}

intent_responses = {
    'activate_my_card': "You can activate your card using our mobile app under the 'Cards' section.",
    'age_limit': "The minimum age to open an account with us is 18 years.",
    'apple_pay_or_google_pay': "Yes, we support Apple Pay and Google Pay. You can link your card through their respective apps.",
    'atm_support': "You can use your card at any ATM that accepts Visa or Mastercard.",
    'automatic_top_up': "To enable automatic top-up, go to the 'Top-up' section in the app and select 'Automatic Top-up'.",
    'balance_not_updated_after_bank_transfer': "Bank transfers can take up to 2-3 business days to reflect in your balance.",
    'balance_not_updated_after_cheque_or_cash_deposit': "Cheque or cash deposits might take 3-5 business days to process. Please check with your bank for specific timelines.",
    'beneficiary_not_allowed': "Please make sure the beneficiary's details are correct and that they meet the transfer requirements.",
    'cancel_transfer': "Transfers can only be canceled if they are still in a 'Pending' state.",
    'card_about_to_expire': "We will automatically send a new card before your current one expires.",
    'card_acceptance': "Your card is accepted anywhere Visa or Mastercard is supported.",
    'card_arrival': "Cards usually arrive within 7-10 business days after ordering.",
    'card_delivery_estimate': "Delivery times may vary by location, but it's generally 7-10 business days.",
    'card_linking': "You can link your card in the app under the 'Cards' section.",
    'card_not_working': "Please check if your card is active and if you have sufficient funds. Contact support if the issue persists.",
    'card_payment_fee_charged': "Certain transactions may incur fees. Check the 'Fees' section in the app for details.",
    'card_payment_not_recognised': "If you don't recognize a payment, you can dispute it in the app under 'Transactions'.",
    'card_payment_wrong_exchange_rate': "Exchange rates are updated regularly. Check the app for real-time rates.",
    'card_swallowed': "If your card was swallowed by an ATM, please report it immediately in the app under 'Cards'.",
    'cash_withdrawal_charge': "Cash withdrawals at ATMs may incur fees. Check the 'Fees' section in the app for details.",
    'cash_withdrawal_not_recognised': "You can report unrecognized withdrawals in the app under 'Transactions'.",
    'change_pin': "You can change your PIN in the app under the 'Cards' section.",
    'compromised_card': "If your card is compromised, please freeze it immediately in the app and contact support.",
    'contactless_not_working': "Make sure contactless is enabled for your card. You can check this in the app.",
    'country_support': "We currently support accounts in multiple countries. Check our website for the full list.",
    'declined_card_payment': "Card payments may be declined for insufficient funds or security reasons. Check the app for details.",
    'declined_cash_withdrawal': "Check if you have sufficient funds and that the ATM supports your card.",
    'declined_transfer': "Transfers may be declined for incorrect beneficiary details or insufficient funds.",
    'direct_debit_payment_not_recognised': "You can view and cancel direct debits in the app under 'Payments'.",
    'disposable_card_limits': "Disposable virtual cards have a spending limit of $2,000 per transaction.",
    'edit_personal_details': "You can update your personal details in the app under 'Settings'.",
    'exchange_charge': "Currency exchange rates may include a small fee. Check the 'Rates' section in the app.",
    'exchange_rate': "Real-time exchange rates are available in the app under 'Currency'.",
    'exchange_via_app': "You can exchange currencies instantly in the app under 'Currency'.",
    'extra_charge_on_statement': "Extra charges may appear due to currency conversion or service fees. Check the app for details.",
    'failed_transfer': "Transfers may fail due to incorrect details or insufficient funds. Check the app for more information.",
    'fiat_currency_support': "We support multiple fiat currencies. Check the app for the full list.",
    'get_disposable_virtual_card': "You can get a disposable virtual card in the app under 'Cards'.",
    'get_physical_card': "You can order a physical card in the app under 'Cards'.",
    'getting_spare_card': "You can order a spare card in the app under 'Cards'.",
    'getting_virtual_card': "You can get a virtual card in the app under 'Cards'.",
    'lost_or_stolen_card': "Please freeze your card immediately in the app and order a replacement under 'Cards'.",
    'lost_or_stolen_phone': "If you've lost your phone, contact support immediately to secure your account.",
    'order_physical_card': "You can order a physical card in the app under 'Cards'.",
    'passcode_forgotten': "You can reset your passcode in the app using the 'Forgot Passcode' option.",
    'pending_card_payment': "Pending payments usually settle within 1-3 business days.",
    'pending_cash_withdrawal': "Pending withdrawals may take up to 1-3 business days to settle.",
    'pending_top_up': "Pending top-ups may take up to 2-3 business days to reflect in your account.",
    'pending_transfer': "Pending transfers usually settle within 1-3 business days.",
    'pin_blocked': "You can unblock your PIN in the app under the 'Cards' section.",
    'receiving_money': "You can receive money by sharing your account details or a payment link.",
    'Refund_not_showing_up': "Refunds usually take 5-10 business days to reflect in your account.",
    'request_refund': "You can request a refund in the app under 'Transactions'.",
    'reverted_card_payment': "Reverted payments usually reflect in your account within 5-10 business days.",
    'supported_cards_and_currencies': "We support multiple cards and currencies. Check the app for the full list.",
    'terminate_account': "To terminate your account, please contact support through the app.",
    'top_up_by_bank_transfer_charge': "Bank transfer top-ups may incur a small fee. Check the app for details.",
    'top_up_by_card_charge': "Card top-ups may incur a small fee. Check the app for details.",
    'top_up_by_cash_or_cheque': "Cash or cheque top-ups can take 3-5 business days to process.",
    'top_up_failed': "Top-ups may fail due to incorrect details or insufficient funds.",
    'top_up_limits': "Top-up limits vary by account type. Check the app for your current limits.",
    'top_up_reverted': "Reverted top-ups usually reflect in your account within 5-10 business days.",
    'topping_up_by_card': "You can top up by card in the app under 'Top-up'.",
    'transaction_charged_twice': "If you've been charged twice, you can report it in the app under 'Transactions'.",
    'transfer_fee_charged': "Transfer fees depend on the amount and currency. Check the app for details.",
    'transfer_into_account': "You can transfer money into your account using bank transfer or payment links.",
    'transfer_not_received_by_recipient': "Transfers may take up to 1-3 business days to reach the recipient.",
    'transfer_timing': "Transfers usually take 1-3 business days, depending on the currency and method.",
    'unable_to_verify_identity': "If you're unable to verify your identity, please contact support for assistance.",
    'verify_my_identity': "You can verify your identity by logging in'.",
    'verify_source_of_funds': "You may need to provide documents to verify the source of funds.",
    'verify_top_up': "You can check your top-up in the chatbot.",
    'virtual_card_not_working': "If your virtual card isn't working, try re-adding it to your wallet or contact support.",
    'visa_or_mastercard': "We issue both Visa and Mastercard. Check the app to see which card type you have.",
    'why_verify_identity': "Identity verification is required for security and to comply with regulations.",
    'wrong_amount_of_cash_received': "If the cash amount is incorrect, report it in the app under 'Transactions'.",
    'wrong_exchange_rate_for_cash_withdrawal': "Exchange rates depend on the time of the transaction."
}

if __name__== '__main__':
    print('why_verify_identity' in intent_responses)
    print(intent_responses['why_verify_identity'])